{% extends "base/configmap.yaml" %}
{% block configmap %}
  jupyter_notebook_config.py: |
    import os
    c.NotebookApp.ip="0.0.0.0"
    c.NotebookApp.port=8888
    c.NotebookApp.token=""
    c.NotebookApp.cookie_secret_file="/etc/jupyter_server_secrets/cookie_secret"
    c.NotebookApp.allow_origin="{{ host_url }}"
    c.NotebookApp.base_url="{{ path }}"
    c.NotebookApp.notebook_dir="{{ jupyter_server["rootDir"] }}"
    c.NotebookApp.default_url="{{ jupyter_server["defaultUrl"] }}"
    c.NotebookApp.allow_remote_access=True

  jupyter_server_config.py: |
    import os
    c.ServerApp.ip="0.0.0.0"
    c.ServerApp.port=8888
    c.ServerApp.token=""
    c.ServerApp.cookie_secret_file="/etc/jupyter_server_secrets/cookie_secret"
    c.ServerApp.allow_origin="{{ host_url }}"
    c.ServerApp.base_url="{{ path }}"
    c.ServerApp.root_dir="{{ jupyter_server["rootDir"] }}"
    c.ServerApp.default_url="{{ jupyter_server["defaultUrl"] }}"
    c.ServerApp.allow_remote_access=True
{% endblock %}
